---
- name: Install GrandPerspective via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 1111570163, name: "GrandPerspective" }
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == true

- name: Install GrandPerspective via Homebrew
  homebrew_cask:
    name: grandperspective
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == false
